#!/bin/sh

uci -q batch <<-EOF
	set network.lan.ipaddr='192.168.26.1'
	set network.lan.netmask='255.255.255.0'
EOF
uci commit network

uci -q batch <<-EOF
	set system.@system[0].timezone='CST-8'
	set system.@system[0].zonename='Asia/Shanghai'

	delete system.ntp.server
	add_list system.ntp.server='ntp1.aliyun.com'
	add_list system.ntp.server='ntp.tencent.com'
	add_list system.ntp.server='ntp.ntsc.ac.cn'
	add_list system.ntp.server='time.apple.com'
EOF
uci commit system

# 单端口 80：/ -> Vue；/luci/ 仅入口页跳转到标准 LuCI 路径（勿改 cgi/ubus 前缀，否则 XHR 失败）
uci -q batch <<-EOF
	delete uhttpd.main.listen_http
	add_list uhttpd.main.listen_http='0.0.0.0:80'
	add_list uhttpd.main.listen_http='[::]:80'
	set uhttpd.main.home='/www'
	set uhttpd.main.cgi_prefix='/cgi-bin'
	set uhttpd.main.ubus_prefix='/ubus'
	set uhttpd.main.ubus_socket='/var/run/ubus/ubus.sock'
	set uhttpd.main.script_timeout='600'
	set uhttpd.main.network_timeout='600'
	set uhttpd.main.max_requests='20'
	delete uhttpd.main.lua_prefix
	delete uhttpd.main.ucode_prefix
EOF

# 移除独立 8080 实例
uci -q delete uhttpd.luci 2>/dev/null

# LuCI 使用 OpenWrt 默认 URL（/cgi-bin/luci、/luci-static、/ubus）
LUC_THEME="$(uci -q get luci.main.mediaurlbase)"
LUC_THEME="${LUC_THEME##*/}"
[ -z "$LUC_THEME" ] && LUC_THEME=bootstrap
uci set luci.main.resourcebase='/luci-static/resources'
uci set luci.main.mediaurlbase="/luci-static/$LUC_THEME"
uci set luci.main.ubuspath='/ubus/'

uci commit luci
uci commit uhttpd
/etc/init.d/uhttpd restart

rm -f /usr/lib/lua/luci/view/admin_status/index/mwan.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/upnp.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/ddns.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/minidlna.htm

rm -f /www/luci-static/resources/view/status/include/70_ddns.js
rm -f /www/luci-static/resources/view/status/include/80_upnp.js

sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/aria2.lua
sed -i 's/services/nas/g' /usr/lib/lua/luci/view/aria2/overview_status.htm
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/hd_idle.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba4.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/minidlna.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/transmission.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/mjpg-streamer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/p910nd.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/usb_printer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/xunlei.lua
sed -i 's/services/nas/g'  /usr/lib/lua/luci/view/minidlna_status.htm

sed -i 's/\"services\"/\"nas\"/g' /usr/share/luci/menu.d/luci-app-samba4.json

sed -i 's#downloads.openwrt.org#mirrors.tencent.com/lede#g' /etc/opkg/distfeeds.conf
sed -i 's#downloads.openwrt.org#mirrors.tencent.com/lede#g' /etc/apk/repositories.d/distfeeds.list
sed -i 's/root::0:0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow
sed -i 's/root:::0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow

sed -i "s/# //g" /etc/opkg/distfeeds.conf
sed -i '/helloworld/d' /etc/opkg/distfeeds.conf
sed -i '/openwrt_luci/ { s/snapshots/releases\/18.06.9/g; }'  /etc/opkg/distfeeds.conf

sed -i '/check_signature/d' /etc/opkg.conf

sed -i '/REDIRECT --to-ports 53/d' /etc/firewall.user

sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='R26.05.20'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='LEDE '" >> /etc/openwrt_release

sed -i '/OPENWRT_RELEASE/d' /usr/lib/os-release
echo 'OPENWRT_RELEASE="LEDE R26.05.20"' >> /usr/lib/os-release

sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

exit 0
