#!/bin/sh

uci -q batch <<-EOF
	set network.lan.ipaddr='192.168.26.1'
	set network.lan.netmask='255.255.255.0'
EOF
uci commit network

uci -q batch <<-EOF
	set system.@system[0].timezone='CST-8'
	set system.@system[0].zonename='Asia/Shanghai'

	delete system.ntp.server
	add_list system.ntp.server='ntp1.aliyun.com'
	add_list system.ntp.server='ntp.tencent.com'
	add_list system.ntp.server='ntp.ntsc.ac.cn'
	add_list system.ntp.server='time.apple.com'
EOF
uci commit system

uci -q batch <<-EOF
	delete uhttpd.main.listen_http
	add_list uhttpd.main.listen_http='0.0.0.0:80'
	add_list uhttpd.main.listen_http='[::]:80'
	delete uhttpd.main.lua_prefix
	delete uhttpd.main.ucode_prefix
	delete uhttpd.main.ubus_prefix
EOF

if ! uci -q get uhttpd.luci >/dev/null 2>&1; then
	uci set uhttpd.luci=uhttpd
fi

uci -q batch <<-EOF
	delete uhttpd.luci.listen_http
	add_list uhttpd.luci.listen_http='0.0.0.0:8080'
	add_list uhttpd.luci.listen_http='[::]:8080'
	set uhttpd.luci.home='/www-luci'
	set uhttpd.luci.cgi_prefix='/cgi-bin'
	set uhttpd.luci.ubus_prefix='/ubus'
	set uhttpd.luci.ubus_socket='/var/run/ubus/ubus.sock'
	set uhttpd.luci.script_timeout='600'
	set uhttpd.luci.network_timeout='600'
	set uhttpd.luci.max_requests='20'
	delete uhttpd.luci.lua_prefix
	delete uhttpd.luci.ucode_prefix
EOF

[ -d /www/luci-static ] && ln -sfn /www/luci-static /www-luci/luci-static
[ -d /www/cgi-bin ] && ln -sfn /www/cgi-bin /www-luci/cgi-bin

[ -f /usr/lib/uhttpd_lua.so ] && \
	uci add_list uhttpd.luci.lua_prefix='/cgi-bin/luci=/usr/lib/lua/luci/sgi/uhttpd.lua'
[ -f /usr/lib/uhttpd_ucode.so ] && \
	uci add_list uhttpd.luci.ucode_prefix='/cgi-bin/luci=/usr/share/ucode/luci/uhttpd.uc'

uci commit uhttpd
/etc/init.d/uhttpd restart

rm -f /usr/lib/lua/luci/view/admin_status/index/mwan.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/upnp.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/ddns.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/minidlna.htm

rm -f /www/luci-static/resources/view/status/include/70_ddns.js
rm -f /www/luci-static/resources/view/status/include/80_upnp.js
sed -i "/view.status.include.50_dsl/d" /www/luci-static/resources/view/status/index.js

sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/aria2.lua
sed -i 's/services/nas/g' /usr/lib/lua/luci/view/aria2/overview_status.htm
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/hd_idle.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba4.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/minidlna.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/transmission.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/mjpg-streamer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/p910nd.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/usb_printer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/xunlei.lua
sed -i 's/services/nas/g'  /usr/lib/lua/luci/view/minidlna_status.htm

sed -i 's/\"services\"/\"nas\"/g' /usr/share/luci/menu.d/luci-app-samba4.json

sed -i 's#downloads.openwrt.org#mirrors.tencent.com/lede#g' /etc/opkg/distfeeds.conf
sed -i 's#downloads.openwrt.org#mirrors.tencent.com/lede#g' /etc/apk/repositories.d/distfeeds.list
sed -i 's/root::0:0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow
sed -i 's/root:::0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow

sed -i "s/# //g" /etc/opkg/distfeeds.conf
sed -i '/helloworld/d' /etc/opkg/distfeeds.conf
sed -i '/openwrt_luci/ { s/snapshots/releases\/18.06.9/g; }'  /etc/opkg/distfeeds.conf

sed -i '/check_signature/d' /etc/opkg.conf

sed -i '/REDIRECT --to-ports 53/d' /etc/firewall.user

sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='R26.05.20'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='LEDE '" >> /etc/openwrt_release

sed -i '/OPENWRT_RELEASE/d' /usr/lib/os-release
echo 'OPENWRT_RELEASE="LEDE R26.05.20"' >> /usr/lib/os-release

sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

exit 0
