#!/bin/sh
# 首次启动兜底（postinst 出镜像时一般已覆盖 /www/index.html）

[ -f /www/erouter/index.html ] && cp -f /www/erouter/index.html /www/index.html
[ -f /www/erouter/favicon.ico ] && cp -f /www/erouter/favicon.ico /www/favicon.ico

exit 0
